### ISSUE TITLE
Not working anymore with RTBF auvio

### ISSUE THREAD

**Issue by mauriceriguel** [zyphos/belgium-replay-tv#11] opened 2017-03-03 11:25 UTC
hello!
first, thank you very much for your work! i've enjoyed it for months!
sadly, yesterday i experienced an issue with this add on with RTBF auvio. only live streams are available and the replay aren't listed anymore.
do you think you can fix the problem? i have no clue how to do it myself.  :-(
i don't care about rtl, but rtbf is a must for me, and especially for my 6 yo daughter who enjoys cartoons very much (and is able to use kodi)...
thanks in advance for your help.
cheers,
mr

**Comment by zyphos** [comment] 2017-03-03 12:42
Duplicate of #10 
https://github.com/zyphos/belgium-replay-tv/issues/10

**Closed as completed by zyphos** 2017-03-03 12:42 UTC
Labels: duplicate

**Comment by mauriceriguel** [comment] 2017-03-03 13:48
sorry but it's not. that's a new issue. the other one was solved.
should i reopen the other issue ? how can i?
